# Generated by Django 5.2.8 on 2025-11-13 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='નામ')),
                ('mobile', models.CharField(max_length=15, verbose_name='મોબાઇલ નંબર')),
                ('address', models.TextField(verbose_name='સરનામું')),
                ('pincode', models.CharField(max_length=10, verbose_name='પિનકોડ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ઓર્ડર તારીખ')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20, verbose_name='સ્થિતિ')),
            ],
            options={
                'verbose_name': 'ઓર્ડર',
                'verbose_name_plural': 'ઓર્ડર્સ',
                'ordering': ['-created_at'],
            },
        ),
    ]
